// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// wpcaCpp
Rcpp::List wpcaCpp(const arma::mat& Y, const int& nPCs, const bool& weighted);
RcppExport SEXP _BFAST_wpcaCpp(SEXP YSEXP, SEXP nPCsSEXP, SEXP weightedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int& >::type nPCs(nPCsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type weighted(weightedSEXP);
    rcpp_result_gen = Rcpp::wrap(wpcaCpp(Y, nPCs, weighted));
    return rcpp_result_gen;
END_RCPP
}
// getneighborhood_fast
arma::sp_umat getneighborhood_fast(const arma::mat y, float radius);
RcppExport SEXP _BFAST_getneighborhood_fast(SEXP ySEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< float >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(getneighborhood_fast(y, radius));
    return rcpp_result_gen;
END_RCPP
}
// ICMEM
Rcpp::List ICMEM(const arma::mat& Y, const arma::ivec& x_int, const arma::sp_mat& Adj, arma::mat& A_int, arma::vec& mu0_int, arma::mat W_int, arma::mat& mu_int, arma::cube& sigma_int, const arma::vec& lambda_grid, const arma::vec& alpha, const arma::vec& beta_grid, const int& maxIter_ICM, const int& maxIter);
RcppExport SEXP _BFAST_ICMEM(SEXP YSEXP, SEXP x_intSEXP, SEXP AdjSEXP, SEXP A_intSEXP, SEXP mu0_intSEXP, SEXP W_intSEXP, SEXP mu_intSEXP, SEXP sigma_intSEXP, SEXP lambda_gridSEXP, SEXP alphaSEXP, SEXP beta_gridSEXP, SEXP maxIter_ICMSEXP, SEXP maxIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type x_int(x_intSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Adj(AdjSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type A_int(A_intSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type mu0_int(mu0_intSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W_int(W_intSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mu_int(mu_intSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type sigma_int(sigma_intSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda_grid(lambda_gridSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_grid(beta_gridSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxIter_ICM(maxIter_ICMSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxIter(maxIterSEXP);
    rcpp_result_gen = Rcpp::wrap(ICMEM(Y, x_int, Adj, A_int, mu0_int, W_int, mu_int, sigma_int, lambda_grid, alpha, beta_grid, maxIter_ICM, maxIter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BFAST_wpcaCpp", (DL_FUNC) &_BFAST_wpcaCpp, 3},
    {"_BFAST_getneighborhood_fast", (DL_FUNC) &_BFAST_getneighborhood_fast, 2},
    {"_BFAST_ICMEM", (DL_FUNC) &_BFAST_ICMEM, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_BFAST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
