# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' wpcaCpp
#' @description
#' an efficient function to find the
#'
#' @param Y is the observed n*p feature matrix.
#' @param nPCs is the number of the principle components.
#'
#' @export
wpcaCpp <- function(Y, nPCs, weighted = TRUE) {
    .Call(`_BFAST_wpcaCpp`, Y, nPCs, weighted)
}

#' @title
#' getneighborhood_fast
#' @description
#' an efficient function to find the neighborhood based on the matrix of position and a pre-defined cutoff
#'
#' @param x is a n-by-2 matrix of position.
#' @param radius is a threashold of Euclidean distance to decide whether a spot is an neighborhood of another spot. For example, if the Euclidean distance between spot A and B is less than cutoff, then A is taken as the neighbourhood of B.
#' @return A sparse matrix containing the neighbourhood
#'
#' @export
getneighborhood_fast <- function(y, radius) {
    .Call(`_BFAST_getneighborhood_fast`, y, radius)
}

#' @title
#' ICMEM
#' @description
#' estimates the joint latent expectations in the E-step.
#'
#' @param Y is a N*p feature matrix
#' @param x_int is a vector of initial cluster label.
#' @param Adj is a matrix containing neighborhood information generated by getneighborhood_fast.
#' @param A_int is an initial p*D factor loading matrix.
#' @param mu0_int is an initial p*1 mean vector.
#' @param W_int is an initial p*p diagonal matrix.
#' @param mu_int is an initial mean vector. we often generated it by Gaussian mixture model.
#' @param theta_int is a initial precision matrix. we often generated it by Gaussian mixture model.
#' @param lambda_grid is a sequence of exponential decay parameter in the zero-inflation model.
#' @param alpha is a intercept.
#' @param beta_grid is a sequence of smoothing parameter that can be specified by user.
#' @param maxiter_ICM is the maximum iteration of ICM algorithm.
#' @param maxiter is the maximum iteration of EM algorithm.
#' @return a list.
#' The item 'x' is the clustering result.
#' The item 'gam' is the posterior probability matrix.
#' The item 'A' is a factor lodading matrix.
#' The item 'mu0' is the mean of the residual.
#' The item 'W' is the variance of the residual.
#' The item 'mu' is the mean of each component.
#' The item 'sigma' is the variance of each component.
#' @export
ICMEM <- function(Y, x_int, Adj, A_int, mu0_int, W_int, mu_int, sigma_int, lambda_grid, alpha, beta_grid, maxIter_ICM, maxIter) {
    .Call(`_BFAST_ICMEM`, Y, x_int, Adj, A_int, mu0_int, W_int, mu_int, sigma_int, lambda_grid, alpha, beta_grid, maxIter_ICM, maxIter)
}

